### ISSUE TITLE
undefined method `map` for nil:NilClass

### ISSUE THREAD

**Issue by webdevotion** [lukeredpath/betabuilder#45]
My Gemfile:

```
source "http://rubygems.org"

gem 'betabuilder', :git => 'git://github.com/lukeredpath/betabuilder.git'
gem 'xcodebuild-rb'
```

Output from `rake beta:archive --trace`:

```
** BUILD SUCCEEDED **

** Execute beta:archive
Archiving build...
rake aborted!
undefined method `map' for nil:NilClass
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194/bundler/gems/betabuilder-c99180332459/lib/beta_builder/archived_build.rb:79:in `write_plist_to'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194/bundler/gems/betabuilder-c99180332459/lib/beta_builder/archived_build.rb:66:in `save_to'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194/bundler/gems/betabuilder-c99180332459/lib/beta_builder.rb:167:in `block (2 levels) in define'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/johndoe/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in `load'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in `<main>'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
/Users/johndoe/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => beta:archive
```

**Comment by webdevotion** [comment]
Removing `config.xcode4_archive_mode = true` from my `Rakefile` did the trick.
